#!/usr/bin/env bash
# installs nginx
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
site_redirect="https://www.youtube.com/watch?v=QH2-TGUlwu4"
append_rewrite="rewrite ^/redirect_me $site_redirect permanent;"
sed -i "/listen \[::\]:80 default_server/a $append_rewrite" $file_path
service nginx restart
