#!/usr/bin/env bash
# installs nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html
site_redirect="https://www.youtube.com/watch?v=QH2-TGUlwu4"
file_path="/etc/nginx/sites-available/default"
string_add="rewrite ^/redirect_me $site_redirect permanent;"
sudo sed -i "/listen \[::\]:80 default_server/a $string_add" $file_path
error_add="error_page 404 /404.html"
echo "Ceci n'est pas une page" > sudo /var/www/html/404.html
sudo sed -i "/listen \[::\]:80 default_server/a $error_add" $file_path
sudo service nginx restart
