#!/usr/bin/env bash
# installs nginx
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
site_redirect="https://www.youtube.com/watch?v=QH2-TGUlwu4"
file_path="/etc/nginx/sites-available/default"
string_add="rewrite ^/redirect_me $site_redirect permanent;"
sed -i "/listen \[::\]:80 default_server/a $string_add" $file_path
error_add="error_page 404 /404.html"
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/listen \[::\]:80 default_server/a $error_add" $file_path
service nginx restart
