#!/usr/bin/env bash
# installs nginx

file_path="/etc/nginx/sites-available/default"

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.html
site_redirect="https://www.youtube.com/watch?v=QH2-TGUlwu4"
append_rewrite="rewrite ^/redirect_me $site_redirect permanent;"
sed -i "/listen \[::\]:80 default_server/a $append_rewrite" $file_path
append_error="error_page 404 /404.html;"
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "/listen \[::\]:80 default_server/a $append_error" $file_path
