#!/usr/bin/env bash
#comments
apt-get -y update
apt-get -y install haproxy
echo -e "\nfrontend web-frontend\n \tbind *:80\n \tmode http\n \tdefault_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo -e "\nbackend web-backend\n \tbalance roundrobin\n \tserver 2216-web-01 35.185.53.142:80 check\n \tserver 2216-web-02 34.73.117.146:80 check" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart