#!/usr/bin/env bash
#comments woow

echo $$ > /var/run/holbertonscript.pid
trap "echo I am invincible!!!" SIGTERM
trap "Y U no love me?!" SIGINT
trap (rm /var/run/holbertonscript.pid) SIGQUIT
while true
do
echo "To infinity and beyond"
sleep 2
done
